import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import { App } from '@capacitor/app';
import { Browser } from '@capacitor/browser';
import './style.css';

const config={url:import.meta.env.VITE_SUPABASE_URL,key:import.meta.env.VITE_SUPABASE_ANON_KEY};
const configured=Boolean(config.url?.startsWith('https://')&&config.key&&!config.key.startsWith('YOUR_'));
const db=configured?createClient(config.url,config.key,{auth:{flowType:'pkce',storageKey:'234mile-driver-auth',detectSessionInUrl:false}}):null;
const passengerDb=configured?createClient(config.url,config.key,{auth:{storageKey:'234mile-passenger-auth',detectSessionInUrl:false}}):null;
const localKey='234mile-pilot-v1';
const readLocal=()=>{try{return JSON.parse(localStorage.getItem(localKey))||{}}catch{return {}}};
const saved=readLocal();
const state={page:'search',user:null,profile:null,vehicle:null,offers:Array.isArray(saved.offers)?saved.offers:[],mine:[],requests:[],myRequests:[],sharedOffer:null,shareCode:null,draft:saved.draft||null,selected:null,query:{from:'',to:'',date:''},notice:'',error:'',loading:false,stale:Boolean(saved.offers?.length),connection:navigator.onLine?'online':'offline',lastSync:saved.lastSync||null};
const root=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const niceDate=value=>{const d=new Date(`${value}T12:00:00`);return Number.isNaN(d.valueOf())?value:d.toLocaleDateString('en-NG',{weekday:'short',day:'numeric',month:'short'})};
const phone=value=>{let n=String(value||'').replace(/\D/g,'');if(n.startsWith('0')&&n.length===11)n='234'+n.slice(1);return /^234[0-9]{10}$/.test(n)?n:null};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const requireOnline=()=>{if(!navigator.onLine)throw Error('Reconnect and try again. Seat changes need a server response.')};
const requestLabel=status=>({pending:'Pending driver confirmation',booked:'Booked',declined:'Declined',cancelled:'Cancelled'}[status]||status);
const selectedOffer=()=>state.sharedOffer?.id===state.selected?state.sharedOffer:state.offers.find(v=>v.id===state.selected);
const publicUrl=()=>import.meta.env.VITE_PUBLIC_APP_URL?.replace(/\/$/,'')||(!Capacitor.isNativePlatform()?location.origin:null);
const shareUrl=o=>{const base=publicUrl();return base?`${base}/?trip=${encodeURIComponent(o.id)}&code=${encodeURIComponent(o.share_code)}`:null};
const isActive=offer=>offer.status==='published'&&offer.seats_available>0&&offer.travel_date>=today();
const persist=()=>localStorage.setItem(localKey,JSON.stringify({offers:state.offers,lastSync:state.lastSync,draft:state.draft}));
const message=(text,error=false)=>{state.notice=error?'':text;state.error=error?text:'';render()};
const busy=async(fn)=>{state.loading=true;render();try{await fn()}catch(error){message(error.message||'Something went wrong. Try again.',true)}finally{state.loading=false;render()}};
const input=(name,label,value='',type='text',extra='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(name,label,value,options)=>`<label class="field"><span>${label}</span><select name="${name}">${options.map(item=>`<option value="${esc(item[0])}" ${item[0]===value?'selected':''}>${esc(item[1])}</option>`).join('')}</select></label>`;
const action=(label,id,kind='primary')=>`<button type="button" class="action ${kind}" data-go="${id}">${label}</button>`;
const route=offer=>`<div class="route"><span class="route-mark hollow"></span><strong>${esc(offer.from_city)}</strong><span class="route-track"></span><span></span><span class="route-mark solid"></span><strong>${esc(offer.to_city)}</strong></div>`;
const offerCard=(offer,detail=false)=>`<article class="offer"><div class="offer-top"><span>${esc(niceDate(offer.travel_date))} · ${esc(offer.departure_time?.slice(0,5))}</span><span class="badge">${offer.status==='published'?'Seats available':esc(offer.status)}</span></div>${route(offer)}<div class="offer-bottom"><div><b>₦${Number(offer.price_per_seat).toLocaleString('en-NG')}</b><small>driver’s price / seat</small></div><div class="seat">${offer.seats_available} seat${offer.seats_available===1?'':'s'} left<small>${esc(offer.vehicle_summary)}</small></div></div>${detail?`<button type="button" class="card-link" data-offer="${esc(offer.id)}">View journey →</button>`:''}</article>`;
const header=(eyebrow,title,description='')=>`<div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${description?`<p class="intro">${description}</p>`:''}`;
const myRequestCard=r=>`<article class="offer"><div class="offer-top"><span>${esc(niceDate(r.travel_date))}</span><span class="badge">${esc(requestLabel(r.status))}</span></div><b>${esc(r.from_city)} → ${esc(r.to_city)}</b><p>${r.status==='booked'?`${r.confirmed_seats} confirmed seat${r.confirmed_seats===1?'':'s'}`:`${r.requested_seats} requested seat${r.requested_seats===1?'':'s'}`}</p></article>`;
const driverRequestCard=r=>`<article class="offer"><div class="offer-top"><span>${esc(r.passenger_name)}</span><span class="badge">${esc(requestLabel(r.status))}</span></div><p>${r.requested_seats} requested · ${esc(r.phone_e164)}</p>${r.status==='pending'?`<form class="form request-confirm" data-request="${esc(r.id)}">${input('confirmed_seats','Seats to confirm',r.requested_seats,'number',`required min="1" max="${r.requested_seats}"`)}${select('source','Count these seats as','new',[['new','New seats'],['external','Already in outside-app count']])}<button class="action amber" type="submit">Confirm booking</button></form><button class="action outline" type="button" data-request-action="decline" data-request="${esc(r.id)}">Decline request</button>`:r.status==='booked'?`<p>${r.confirmed_seats} booked seat${r.confirmed_seats===1?'':'s'}</p><button class="action outline" type="button" data-request-action="cancel" data-request="${esc(r.id)}">Cancel booking and release seats</button>`:''}</article>`;
function render(){
  const driver=['driver','setup','vehicle','documents','post','manage'].includes(state.page);
  let body='';const visible=state.offers.filter(isActive).filter(o=>(!state.query.from||o.from_city.toLowerCase().includes(state.query.from.toLowerCase()))&&(!state.query.to||o.to_city.toLowerCase().includes(state.query.to.toLowerCase()))&&(!state.query.date||o.travel_date===state.query.date));
  switch(state.page){
    case 'search':body=`<section class="hero"><div class="eyebrow">LONG-DISTANCE TRAVEL ACROSS NIGERIA</div><h1 class="one-line-title">Find your next ride.</h1><p class="hero-short">Go city to city with a driver heading your way.</p></section><form id="search-form" class="form search-form"><div class="two">${input('from','Leaving from — city or state',state.query.from)}${input('to','Going to — city or state',state.query.to)}</div>${input('date','Departure date',state.query.date,'date',`min="${today()}"`)}<button class="action amber" type="submit">Search interstate journeys →</button></form><div class="section-row"><h2>Upcoming interstate journeys</h2><span>${visible.length}</span></div>${visible.length?visible.map(o=>offerCard(o,true)).join(''):`<div class="empty">No interstate journeys match this search yet. Try another city, state or date.</div>`}${state.stale?`<div class="notice warn">Showing saved listings from ${esc(state.lastSync||'an earlier visit')}. Confirm availability with the driver.</div>`:''}<div class="home-tools"><details class="utility-panel"><summary><span><b>Already arranged a seat?</b><small>Open the private journey link your driver sent.</small></span><i>＋</i></summary><div class="utility-body"><form id="shared-form" class="form">${input('shared_link','Driver’s shared journey link','','url','required')}<button class="action outline" type="submit">Open shared journey</button></form></div></details><details class="utility-panel ${state.myRequests.length?'has-activity':''}"><summary><span><b>Your seat requests</b><small>${state.myRequests.length?`${state.myRequests.length} request${state.myRequests.length===1?'':'s'} on this device`:'Track requests made on this device.'}</small></span><i>＋</i></summary><div class="utility-body">${state.myRequests.length?state.myRequests.map(myRequestCard).join(''):`<div class="empty compact-empty">No seat requests on this device yet.</div>`}${action('Refresh request status','refresh-requests','outline')}</div></details></div>`;break;
    case 'detail':{const o=selectedOffer();if(!o){state.page='search';return render()}const existing=state.myRequests.find(r=>r.offer_id===o.id&&['pending','booked'].includes(r.status));body=header('JOURNEY DETAILS',`${esc(o.from_city)} →<br>${esc(o.to_city)}`,`${esc(niceDate(o.travel_date))} · ${esc(o.departure_time.slice(0,5))} departure`)+offerCard(o)+`<div class="driver-line"><span class="avatar">${esc(o.driver_name.slice(0,1).toUpperCase())}</span><div><b>${esc(o.driver_name)}</b><small>Details supplied by driver</small></div></div><div class="facts"><div><span>Pickup</span><b>${esc(o.pickup)}</b></div><div><span>Drop-off</span><b>${esc(o.dropoff)}</b></div><div><span>Vehicle</span><b>${esc(o.vehicle_summary)}</b></div></div><div class="notice">Document authenticity has not been checked. Confirm the trip, pickup and price directly with the driver. Calling or messaging does not reserve a seat.</div>${o.status==='full'?`<div class="notice warn">This journey is full. Only customers with the driver’s shared link can record seats already arranged outside the app.</div>`:`<div class="two">${action('Call driver','call','outline')}${action('WhatsApp','whatsapp','amber')}</div>`}${existing?`<div class="notice success">Your request is ${esc(requestLabel(existing.status))}. ${existing.status==='booked'?`${existing.confirmed_seats} seats confirmed.`:'The driver must confirm it before seats are booked.'}</div>`:`<h2>Already arranged your seats?</h2><p class="intro">Tell the driver here after you have agreed by call or WhatsApp.</p><form id="request-form" class="form">${input('passenger_name','Your name','','text','required minlength="2" maxlength="80"')}${input('phone','Phone used with driver','','tel','required inputmode="tel"')}${input('requested_seats','Seats arranged',1,'number',`required min="1" max="${o.status==='full'?o.external_seats:Math.max(o.seats_available,o.external_seats)}"`)}<button class="action amber" type="submit">Send for driver confirmation</button></form><div class="notice">This is a request, not a booked seat. Only the driver can confirm it.</div>`}`;break}
    case 'driver':body=`<section class="hero"><div class="eyebrow">INTERSTATE DRIVER MODE</div><h1 class="${state.profile?'':'one-line-title'}">${state.profile?`Plan your next journey, ${esc(state.profile.display_name.split(' ')[0])}.`:'Publish your next journey.'}</h1><p>Share your route, departure time, seats and fare.</p></section>${!configured?`<div class="notice warn">Connect a Supabase project to sign in and publish journeys. You can save a local draft now.</div>${action('Create a local draft','post','amber')}`:!state.user?`<div class="soft-callout"><b>Keep your driver profile across updates</b><span>Sign in with Google to publish a journey.</span></div>${action('Continue with Google','login','amber')}${action('Create a local draft','post','outline')}`:!state.profile?`<div class="soft-callout"><b>Complete driver setup</b><span>Add your name and phone before publishing.</span></div>${action('Set up profile','setup','amber')}`:`${action('Publish a journey','post','amber')}`}<div class="section-row"><h2>Your interstate journeys</h2></div>${state.draft?`<div class="draft"><b>Local draft</b><span>${esc(state.draft.from_city)} → ${esc(state.draft.to_city)} · Not published</span>${action('Continue draft','post','outline')}</div>`:''}${state.mine.length?state.mine.map(o=>`${offerCard(o)}<div class="seat-summary">${o.confirmed_seats||0} booked in app · ${o.external_seats||0} outside app · ${state.requests.filter(r=>r.offer_id===o.id&&r.status==='pending').length} pending</div><button class="card-link" data-manage="${esc(o.id)}">Manage journey →</button>`).join(''):'<div class="empty">Your published interstate journeys will appear here.</div>'}<div class="notice">Confirm passenger requests and count customers arranged outside the app. Pending requests do not fill seats.</div>`;break;
    case 'setup':body=header('DRIVER SETUP','Let’s start with you.','Your name and contact number stay with your account.')+`<form id="profile-form" class="form">${input('display_name','Full name',state.profile?.display_name||state.user?.user_metadata?.full_name||'','','required maxlength="80"')}${input('phone','Phone for calls and WhatsApp',state.profile?.phone_e164||'','tel','required inputmode="tel"')}<button class="action amber" type="submit">Save and continue</button></form><div class="notice">Passengers see your name and can use the phone number on published journeys.</div>`;break;
    case 'vehicle':body=header('YOUR VEHICLE','Tell us about the ride.','The registered owner can be someone other than the driver.')+`<form id="vehicle-form" class="form">${select('relationship','Vehicle relationship',state.vehicle?.relationship||'company',[['owned','I own it'],['company','Company vehicle'],['rented','Rented vehicle'],['borrowed','Borrowed vehicle']])}${input('registered_owner','Registered owner',state.vehicle?.registered_owner||'','','required') }<div class="two">${input('make','Make',state.vehicle?.make||'','','required')}${input('model','Model',state.vehicle?.model||'','','required')}</div>${input('colour','Colour',state.vehicle?.colour||'')}${input('plate_number','Plate number',state.vehicle?.plate_number||'','','required')}<button class="action amber" type="submit">Save vehicle</button></form>`;break;
    case 'documents':body=header('DOCUMENT RECORDS','Keep the details together.','Upload documents and enter the details you can read from them.')+`<form id="document-form" class="form">${select('kind','Document type','licence',[['licence','Driver’s licence'],['vehicle_particulars','Vehicle particulars']])}<label class="field"><span>Document image or PDF · 5 MB maximum</span><input name="file" type="file" accept="image/jpeg,image/png,application/pdf" required></label>${input('document_number','Licence or document number')}${input('name_on_document','Name on document')}${input('plate_on_document','Plate on document')}<label class="check"><input type="checkbox" name="checked" required><span>I checked and corrected these details against the document.</span></label><button class="action amber" type="submit">Save document record</button></form><div class="notice">Files are private to your account. Data is collected, not authenticated. Automatic OCR is not enabled in this pilot.</div>`;break;
    case 'post':{const d=state.draft||{};body=header('NEW INTERSTATE JOURNEY','Share your city-to-city route.','Your fare is displayed exactly as you enter it. 234Mile adds no fee.')+`<form id="post-form" class="form"><div class="two">${input('from_city','Departure city or state',d.from_city||'','','required maxlength="50"')}${input('to_city','Destination city or state',d.to_city||'','','required maxlength="50"')}</div><div class="two">${input('travel_date','Departure date',d.travel_date||'','date',`required min="${today()}"`)}${input('departure_time','Departure time',d.departure_time||'','time','required')}</div>${input('pickup','Pickup landmark',d.pickup||'','','required maxlength="120"')}${input('dropoff','Arrival area',d.dropoff||'','','required maxlength="120"')}<div class="two">${input('seat_capacity','Passenger seat capacity',d.seat_capacity??4,'number','required min="1" max="20"')}${input('price_per_seat','Your fare per seat (₦)',d.price_per_seat??'','number','required min="1" max="1000000"')}</div><button class="action amber" type="submit">Publish interstate journey</button><button type="button" class="action outline" data-go="save-draft">Save local draft</button></form><div class="notice">Four passenger seats are the default. Change the number for a larger vehicle. Publishing requires a connection.</div>`;break}
    case 'manage':{const o=state.mine.find(v=>v.id===state.selected);if(!o){state.page='driver';return render()}const requests=state.requests.filter(r=>r.offer_id===o.id);body=header('MANAGE JOURNEY','Stay in control.','Confirm passenger requests and keep seat counts accurate.')+offerCard(o)+`<div class="facts"><div><span>Capacity</span><b>${o.seat_capacity} seats</b></div><div><span>Booked in app</span><b>${o.confirmed_seats} seats</b></div><div><span>Arranged outside app</span><b>${o.external_seats} seats</b></div><div><span>Pending requests</span><b>${requests.filter(r=>r.status==='pending').length}</b></div><div><span>Remaining</span><b>${o.seats_available} seats</b></div></div><form id="manage-form" class="form"><div class="two">${input('seat_capacity','Passenger seat capacity',o.seat_capacity,'number','required min="1" max="20"')}${input('external_seats','Seats booked outside app',o.external_seats,'number','required min="0" max="20"')}</div><button class="action amber" type="submit">Save seat counts</button></form><div class="notice">If a customer you already counted outside the app submits a request, choose “Already in outside-app count” when confirming. That moves their seats without counting them twice.</div><h2>Passenger requests</h2>${requests.length?requests.map(driverRequestCard).join(''):'<div class="empty">No passenger requests yet.</div>'}<h2>Share with existing customers</h2>${shareUrl(o)?`${input('share_link','Unlisted trip link',shareUrl(o),'url','readonly')}${action('Copy trip link','copy-link','outline')}`:'<div class="notice warn">Set VITE_PUBLIC_APP_URL to your hosted web app URL to share a trip link from Android.</div>'}${action('Cancel journey','cancel','outline')}<div class="notice">Seat changes require a connection. Contact affected passengers directly if you cancel.</div>`;break}
    case 'account':body=header('YOUR ACCOUNT','One app. Two ways to travel.')+`<div class="facts"><div><span>Sign-in</span><b>${state.user?esc(state.user.email||'Google account'):'Guest passenger'}</b></div><div><span>Driver details</span><b>${state.profile?esc(state.profile.display_name):'Not set up'}</b></div><div><span>Vehicle</span><b>${state.vehicle?esc(`${state.vehicle.make} ${state.vehicle.model}`):'Not added'}</b></div></div>${state.user?`${action('Edit driver profile','setup','outline')}${action('Edit vehicle','vehicle','outline')}${action('Document records','documents','outline')}${action('Sign out','logout','quiet')}`:configured?action('Continue with Google','login','amber'):''}<div class="notice">Documents are collected for records. Authenticity is not verified.</div>`;break;
  }
  const nav=state.page==='detail'?`<button data-go="search">← Back to rides</button>`:'';
  root.innerHTML=`<div class="shell"><header class="top"><b class="brand">234<span>mile</span></b><span class="mode">${driver?'DRIVER':state.page==='account'?'ACCOUNT':'PASSENGER'}</span></header>${!configured?'<div class="status amber-status">Local mode · Supabase setup needed for shared journeys</div>':state.connection==='offline'?'<div class="status">Offline · cached listings and drafts only</div>':''}<main>${nav}${body}${state.error?`<div class="notice error" role="alert">${esc(state.error)}</div>`:''}${state.notice?`<div class="notice success" role="status">${esc(state.notice)}</div>`:''}</main><nav class="bottom" aria-label="Main navigation"><button data-go="search" class="${['search','detail'].includes(state.page)?'current':''}">⌕<small>Find journeys</small></button><button data-go="driver" class="${driver?'current':''}">＋<small>Drive interstate</small></button><button data-go="account" class="${state.page==='account'?'current':''}">○<small>Account</small></button></nav></div>`;
  if(state.page==='detail'&&selectedOffer()?.status==='full'&&!selectedOffer()?.external_seats){const form=root.querySelector('#request-form');if(form)form.innerHTML='<div class="notice warn">No outside-app seats remain to record on this trip. Contact the driver if your arrangement is missing.</div>'}
  root.querySelectorAll('button').forEach(button=>button.disabled=state.loading);
}
async function refresh(){if(!db){state.stale=Boolean(state.offers.length);render();return}try{
  const {data,error}=await db.from('ride_offers').select('*').eq('status','published').gt('seats_available',0).gte('travel_date',today()).order('travel_date',{ascending:true}).limit(100);
  if(error)throw error;state.offers=data||[];state.lastSync=new Date().toLocaleString('en-NG');state.stale=false;persist();
}catch{state.stale=Boolean(state.offers.length);state.error='Could not refresh journeys. Saved listings may be out of date.'}render()}
async function loadMine(){if(!db||!state.user)return;const {data,error}=await db.from('ride_offers').select('*').eq('driver_id',state.user.id).order('travel_date',{ascending:false});if(error)throw error;state.mine=data||[];if(state.mine.length){const ids=state.mine.map(o=>o.id);const result=await db.from('seat_requests').select('*').in('offer_id',ids).order('created_at',{ascending:false});if(result.error)throw result.error;state.requests=result.data||[]}else state.requests=[]}
async function loadMyRequests(){if(!passengerDb)return;const {data:session}=await passengerDb.auth.getSession();if(!session.session){state.myRequests=[];render();return}const {data,error}=await passengerDb.rpc('get_my_seat_requests');if(error)throw error;state.myRequests=data||[];render()}
async function openSharedLink(link){requireOnline();if(!passengerDb)throw Error('Connect Supabase before opening a shared trip.');let url;try{url=new URL(link)}catch{throw Error('Paste the complete trip link from your driver.')}if(url.origin!==publicUrl())throw Error('This trip link is not for this 234Mile app.');const id=url.searchParams.get('trip'),code=url.searchParams.get('code');if(!id||!code)throw Error('The trip link is incomplete.');const {data,error}=await passengerDb.rpc('get_shared_offer',{p_offer_id:id,p_share_code:code});if(error)throw error;if(!data?.length)throw Error('This trip link is invalid or the journey has ended.');state.sharedOffer=data[0];state.shareCode=code;state.selected=id;state.page='detail';history.replaceState(null,'',location.pathname);render()}
async function submitRequest(form){requireOnline();if(!passengerDb)throw Error('Connect Supabase to send a seat request.');const f=new FormData(form),name=String(f.get('passenger_name')||'').trim(),number=phone(f.get('phone')),seats=Number(f.get('requested_seats')),o=selectedOffer();if(!o||!name||!number||!Number.isInteger(seats)||seats<1)throw Error('Enter your name, Nigerian phone number and seat quantity.');let {data:session}=await passengerDb.auth.getSession();if(!session.session){const created=await passengerDb.auth.signInAnonymously();if(created.error)throw created.error;session=created.data}if(!session.session)throw Error('Could not start a passenger session. Try again.');const {error}=await passengerDb.rpc('submit_seat_request',{p_offer_id:o.id,p_share_code:state.shareCode,p_name:name,p_phone:number,p_seats:seats});if(error)throw error;await loadMyRequests();state.notice='Request sent. It is pending until the driver confirms your seats.'}
async function loadAccount(){if(!db||!state.user){state.profile=null;state.vehicle=null;state.mine=[];return}const [p,v]=await Promise.all([db.from('driver_profiles').select('*').eq('user_id',state.user.id).maybeSingle(),db.from('vehicles').select('*').eq('driver_id',state.user.id).order('created_at',{ascending:false}).limit(1)]);if(p.error)throw p.error;if(v.error)throw v.error;state.profile=p.data;state.vehicle=v.data?.[0]||null;await loadMine()}
async function signIn(){if(!db)return message('Connect a Supabase project first.',true);const native=Capacitor.isNativePlatform();const {data,error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:native?'app.mile234://auth/callback':location.origin,skipBrowserRedirect:native}});if(error)throw error;if(native&&data?.url)await Browser.open({url:data.url})}
async function submitProfile(form){if(!db||!state.user)throw Error('Sign in to save your profile.');const f=new FormData(form),number=phone(f.get('phone'));if(!number)throw Error('Enter a Nigerian mobile number, such as 08012345678.');const name=String(f.get('display_name')||'').trim();if(name.length<2)throw Error('Enter your full name.');const {error}=await db.from('driver_profiles').upsert({user_id:state.user.id,display_name:name,phone_e164:number,updated_at:new Date().toISOString()});if(error)throw error;await loadAccount();state.page='vehicle';state.notice='Driver profile saved.'}
async function submitVehicle(form){if(!db||!state.user)throw Error('Sign in to save your vehicle.');const f=new FormData(form);const v={driver_id:state.user.id,relationship:String(f.get('relationship')),registered_owner:String(f.get('registered_owner')).trim(),make:String(f.get('make')).trim(),model:String(f.get('model')).trim(),colour:String(f.get('colour')).trim(),plate_number:String(f.get('plate_number')).trim().toUpperCase()};if(Object.values(v).some((x,i)=>i!==5&&!x))throw Error('Complete the vehicle details.');if(state.vehicle)v.id=state.vehicle.id;const {error}=await db.from('vehicles').upsert(v);if(error)throw error;await loadAccount();state.page='driver';state.notice='Vehicle saved. You can now post a journey.'}
async function submitDocument(form){if(!db||!state.user)throw Error('Sign in to save documents.');const f=new FormData(form),file=f.get('file');if(!(file instanceof File)||!file.size)throw Error('Choose a document.');if(file.size>5*1024*1024||!['image/jpeg','image/png','application/pdf'].includes(file.type))throw Error('Use a JPG, PNG or PDF under 5 MB.');const path=`${state.user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9.\-_]/g,'_')}`;const upload=await db.storage.from('driver-documents').upload(path,file,{contentType:file.type});if(upload.error)throw upload.error;const record={driver_id:state.user.id,vehicle_id:state.vehicle?.id||null,kind:String(f.get('kind')),storage_path:path,document_number:String(f.get('document_number')||'').trim(),name_on_document:String(f.get('name_on_document')||'').trim(),plate_on_document:String(f.get('plate_on_document')||'').trim(),status:'driver_corrected'};const {error}=await db.from('driver_documents').insert(record);if(error)throw error;state.notice='Private document record saved. Authenticity has not been checked.'}
function tripFromForm(form){const f=new FormData(form),trip={from_city:String(f.get('from_city')||'').trim(),to_city:String(f.get('to_city')||'').trim(),travel_date:String(f.get('travel_date')||''),departure_time:String(f.get('departure_time')||''),pickup:String(f.get('pickup')||'').trim(),dropoff:String(f.get('dropoff')||'').trim(),seat_capacity:Number(f.get('seat_capacity')),price_per_seat:Number(f.get('price_per_seat'))};if(!trip.from_city||!trip.to_city||trip.from_city.toLowerCase()===trip.to_city.toLowerCase())throw Error('Choose two different cities.');if(!trip.travel_date||trip.travel_date<today()||!trip.departure_time||!trip.pickup||!trip.dropoff||!Number.isInteger(trip.seat_capacity)||trip.seat_capacity<1||trip.seat_capacity>20||trip.price_per_seat<1||trip.price_per_seat>1000000)throw Error('Complete the date, time, places, seats and price.');return trip}
async function publish(form){const trip=tripFromForm(form);state.draft=trip;persist();if(!db||!state.user)throw Error('Draft saved on this device. Connect Supabase and sign in to publish.');if(!state.profile)throw Error('Draft saved. Complete your driver profile before publishing.');if(!navigator.onLine)throw Error('Draft saved. Reconnect and tap Publish journey again.');const payload={...trip,seats_available:trip.seat_capacity,driver_id:state.user.id,vehicle_id:state.vehicle?.id||null,driver_name:state.profile.display_name,phone_e164:state.profile.phone_e164,vehicle_summary:state.vehicle?`${state.vehicle.make} ${state.vehicle.model} · ${state.vehicle.colour||''}`.trim():'Vehicle details on request',status:'published'};const {error}=await db.from('ride_offers').insert(payload);if(error)throw error;state.draft=null;persist();await Promise.all([loadMine(),refresh()]);state.page='driver';state.notice='Journey published to the shared listings.'}
async function updateSeats(form){requireOnline();const f=new FormData(form),capacity=Number(f.get('seat_capacity')),external=Number(f.get('external_seats'));if(!Number.isInteger(capacity)||!Number.isInteger(external))throw Error('Enter whole seat counts.');const {error}=await db.rpc('set_ride_inventory',{p_offer_id:state.selected,p_capacity:capacity,p_external:external});if(error)throw error;await Promise.all([loadMine(),refresh()]);state.notice='Seat counts updated.'}
async function decideRequest(id,kind,form){requireOnline();const args=kind==='confirm'?{p_request_id:id,p_seats:Number(new FormData(form).get('confirmed_seats')),p_from_external:new FormData(form).get('source')==='external'}:{p_request_id:id};const name=kind==='confirm'?'confirm_seat_request':kind==='decline'?'decline_seat_request':'cancel_seat_booking';const {error}=await db.rpc(name,args);if(error)throw error;await Promise.all([loadMine(),refresh()]);state.notice=kind==='confirm'?'Booking confirmed.':kind==='decline'?'Request declined.':'Booking cancelled and seats released.'}
async function cancel(){if(!confirm('Cancel this journey? Contact any passengers you already arranged to carry.'))return;requireOnline();const {error}=await db.rpc('cancel_ride',{p_offer_id:state.selected});if(error)throw error;await Promise.all([loadMine(),refresh()]);state.page='driver';state.notice='Journey cancelled. Contact anyone you arranged to carry.'}
root.addEventListener('submit',event=>{event.preventDefault();const form=event.target;state.error='';state.notice='';if(form.id==='search-form'){const f=new FormData(form);state.query={from:String(f.get('from')||'').trim(),to:String(f.get('to')||'').trim(),date:String(f.get('date')||'')};render();return}busy(async()=>{if(form.id==='shared-form')await openSharedLink(String(new FormData(form).get('shared_link')||''));if(form.id==='request-form')await submitRequest(form);if(form.classList.contains('request-confirm'))await decideRequest(form.dataset.request,'confirm',form);if(form.id==='profile-form')await submitProfile(form);if(form.id==='vehicle-form')await submitVehicle(form);if(form.id==='document-form')await submitDocument(form);if(form.id==='post-form')await publish(form);if(form.id==='manage-form')await updateSeats(form)})});
root.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;const id=target.dataset.offer||target.dataset.manage;if(id){state.selected=id;state.sharedOffer=null;state.shareCode=null;state.page=target.dataset.offer?'detail':'manage';state.error='';state.notice='';render();return}const requestAction=target.dataset.requestAction;if(requestAction)return busy(()=>decideRequest(target.dataset.request,requestAction));const go=target.dataset.go;if(!go)return;state.error='';state.notice='';if(go==='login')return busy(signIn);if(go==='logout')return busy(async()=>{await db.auth.signOut();state.user=null;state.profile=null;state.vehicle=null;state.mine=[];state.requests=[];state.page='search'});if(go==='refresh-requests')return busy(loadMyRequests);if(go==='copy-link')return busy(async()=>{const o=state.mine.find(v=>v.id===state.selected),link=o&&shareUrl(o);if(!link)throw Error('Set the hosted web app URL first.');if(navigator.share){try{await navigator.share({title:'234Mile interstate journey',url:link});state.notice='Journey link shared.';return}catch(e){if(e.name==='AbortError')return}}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(link);state.notice='Journey link copied.';return}const field=root.querySelector('input[name="share_link"]');field?.focus();field?.select();state.notice='Select and copy the journey link shown above.'});if(go==='cancel')return busy(cancel);if(go==='save-draft'){try{state.draft=tripFromForm(root.querySelector('#post-form'));persist();state.page='driver';message('Draft saved on this device. It has not been published.')}catch(e){message(e.message,true)}return}if(go==='call'||go==='whatsapp'){const o=selectedOffer(),number=phone(o?.phone_e164);if(!o||!isActive(o)||!number)return message('Contact details are unavailable. Refresh the listing.',true);if(go==='call')location.href=`tel:+${number}`;else{const text=`Hello ${o.driver_name}, I saw your ${o.from_city} to ${o.to_city} interstate journey on ${niceDate(o.travel_date)} at ₦${o.price_per_seat} per seat on 234Mile. Are seats still available?`;window.open(`https://wa.me/${number}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}return}state.page=go;render()});
window.addEventListener('online',()=>{state.connection='online';refresh()});window.addEventListener('offline',()=>{state.connection='offline';state.stale=Boolean(state.offers.length);render()});
async function init(){render();if(!db)return;const params=new URLSearchParams(location.search),native=Capacitor.isNativePlatform();if(!native&&params.has('code')&&!params.has('trip')){const {error}=await db.auth.exchangeCodeForSession(params.get('code'));if(error){message(`Sign-in failed: ${error.message}`,true)}else{history.replaceState(null,'',location.pathname);state.page='driver';state.notice='Signed in. Complete your driver profile to post a journey.'}}const {data}=await db.auth.getSession();state.user=data.session?.user||null;try{await loadAccount()}catch(e){state.error=`Account could not load: ${e.message}`}db.auth.onAuthStateChange((_event,session)=>{if(state.user?.id===session?.user?.id)return;state.user=session?.user||null;setTimeout(async()=>{try{await loadAccount();render()}catch(e){message(e.message,true)}},0)});if(native){await App.addListener('appUrlOpen',async({url})=>{if(!url.startsWith('app.mile234://auth/callback'))return;try{const code=new URL(url).searchParams.get('code');if(code){const {error}=await db.auth.exchangeCodeForSession(code);if(error)throw error;await Browser.close();state.page='driver';message('Signed in. Complete your driver profile to post a journey.')}}catch(e){message(`Sign-in failed: ${e.message}`,true)}})}await Promise.all([refresh(),loadMyRequests()]);if(params.has('trip')&&params.has('code')){const link=location.href;try{await openSharedLink(link)}catch(e){message(e.message,true)}}render()}
init();
if('serviceWorker' in navigator&&!Capacitor.isNativePlatform())window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));

